### ISSUE TITLE
Idea: universal CSS file for examples

### ISSUE THREAD

**Issue by lindapaiste** [ml5js/ml5-next-gen#12]
I think it would make a huge difference if we could have a `style.css` file which we load into all of our examples. We would define styles for HTML elements like `h1`, `canvas`, `p`, etc. (not CSS class names).

We would need to add a `<style>` tag to all examples, alongside our `<script>` tags.  It could be done with a one-time manual copy & paste or dynamically with the copy-webpack-plugin, which we use for transforming script urls.  We can easily re-theme by changing that one `style.css` file.

Here is a quick proof-of-concept. I styled the canvas using the same style as the search box on the examples home page.  I centered the contents horizontally which makes a big difference on large screens.

### After 👍 
![image](https://user-images.githubusercontent.com/28965286/170575109-f4e14727-4f84-463b-89ed-655f0f30d7b9.png)

### Before 👎 
![image](https://user-images.githubusercontent.com/28965286/170576033-9ec6724c-d680-405a-8569-020ecea0a5bd.png)

### CSS 👩‍💻 
```css
body {
    font-family: Arial, Helvetica, sans-serif;
    font-size: 16px;
    display: flex;
    flex-direction: column;
    align-items: center;
}

canvas {
    border: 2px solid black;
    padding: 1rem;
    box-shadow: 1rem 1rem #a15ffb;
    margin: 1rem 2rem 2rem 2rem;
}

h1 {
    text-align: center;
    border-bottom: 2px dotted #a15ffb;
    width: fit-content;
    padding-bottom: 8px;
    
}

p {
    max-width: 600px;
}
```
